CREATE TABLE shift (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cupping INTEGER  NULL,
    vault_money money NULL,
    shift_money money NULL,
    jetwash money NULL,
    galp_fleet money NULL,
    local_credit money NULL,
    affractions money NULL,
    discount_card money NULL,
    discount money NULL,
    intern_consumption money NULL,
    devolutions money NULL,
    escapes money NULL,
    resume_genesis money NULL,
    atm money NULL,
    visa money NULL,
    date_created TIMESTAMP DEFAULT now() NULL
);